INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298202','2054062102',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298203','2054062103',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298204','2054062104',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298205','2054062105',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298206','2054062106',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298207','2054062107',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298208','2054062108',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298209','2054062109',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298210','2054062110',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298211','2054062111',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298212','2054062112',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298213','2054062113',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298214','2054062114',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298215','2054062115',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298216','2054062116',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298217','2054062117',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298218','2054062118',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298219','2054062119',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298220','2054062120',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298221','2054062121',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298222','2054062122',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298223','2054062123',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298224','2054062124',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298225','2054062125',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298226','2054062126',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298227','2054062127',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298228','2054062128',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298229','2054062129',0,CONVERT(varchar,getDate(),21),'Just some little cash winning to disburse',CONVERT(varchar,getDate(),21),'Access Bank');
INSERT INTO [dbo].[GenerateCashRequests]
      ([SubscriberId]
      ,[AccountNumber]
      ,[Approved]
      ,[ApprovalDate]
      ,[Description]
      ,[DateWon]
      ,[BankName]) VALUES('1248298230','2054062130',1,CONVERT(varchar,'2023-02-19',21),'Just some little cash winning to disburse',CONVERT(varchar,'2023-02-19',21),'Zenith Bank');
